# Generated by Django 5.2.4 on 2025-07-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='phone',
            new_name='telefone',
        ),
    ]
