# Generated by Django 5.2.4 on 2025-07-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_phone_transaction_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='telefone',
            new_name='phone',
        ),
    ]
